(define (problem pb2)
	(:domain assignment3)
	(:requirements :strips)
	(:objects Greece Cyprus Italy Spain
				Athens Thessaloniki Larnaka Limassol Rome Bari Madrid 
				warehouse_athens port_athens station_athens 
				warehouse_thessaloniki port_thessaloniki station_thessaloniki 
				port_larnaka 
				port_limassol
				warehouse_rome station_rome
				warehouse_bari port_bari station_bari
				warehouse_madrid station_madrid
				ship1 ship2 ship3 ship4 ship5
				truck1 truck2 truck3 truck4 truck5 truck6 truck7 truck8 truck9 truck10 truck11 truck12 truck13 truck14
				locomotive1 locomotive2 locomotive3 locomotive4 locomotive5
				wagon1 wagon2 wagon3 wagon4 wagon5 wagon6 wagon7 wagon8 wagon9 wagon10 wagon11 wagon12 wagon13 wagon14 wagon15
				package1 package2 package3 package4 package5 package6 package7 package8 package9 package10 package11 package12 package13 package14 package15 package16 package17 package18 package19 package20)
				
	(:init
		(is_country Greece)
		(is_country Cyprus)
		(is_country Italy)
		(is_country Spain)
		(is_city Athens)
		(is_city Thessaloniki)
		(is_city Larnaka)
		(is_city Limassol) 
		(is_city Rome) 
		(is_city Bari)
		(is_city Madrid)
		(is_location warehouse_athens)
		(is_location port_athens)
		(is_location station_athens)
		(is_location warehouse_thessaloniki)
		(is_location port_thessaloniki)
		(is_location station_thessaloniki)
		(is_location port_larnaka)
		(is_location port_limassol)
		(is_location warehouse_rome)
		(is_location station_rome)
		(is_location warehouse_bari)
		(is_location port_bari)
		(is_location station_bari)
		(is_location warehouse_madrid)
		(is_location station_madrid)
		(is_port port_athens)
		(is_port port_thessaloniki)
		(is_port port_larnaka)
		(is_port port_limassol)
		(is_port port_bari)
		(is_ship ship1)
		(is_ship ship2)
		(is_ship ship3)
		(is_ship ship4)
		(is_ship ship5)
		(is_truck truck1)
		(is_truck truck2)
		(is_truck truck3)
		(is_truck truck4)
		(is_truck truck5)
		(is_truck truck6)
		(is_truck truck7)
		(is_truck truck8)
		(is_truck truck9)
		(is_truck truck10)
		(is_truck truck11)
		(is_truck truck12)
		(is_truck truck13)
		(is_truck truck14)
		(is_locomotive locomotive1)
		(is_locomotive locomotive2)
		(is_locomotive locomotive3)
		(is_locomotive locomotive4)
		(is_locomotive locomotive5)
		(is_wagon wagon1) 
		(is_wagon wagon2)
		(is_wagon wagon3)
		(is_wagon wagon4) 
		(is_wagon wagon5) 
		(is_wagon wagon6)
		(is_wagon wagon7)
		(is_wagon wagon8) 
		(is_wagon wagon9)
		(is_wagon wagon10)
		(is_wagon wagon11) 
		(is_wagon wagon12) 
		(is_wagon wagon13)
		(is_wagon wagon14)
		(is_wagon wagon15)
		(is_package package1)
		(is_package package2) 
		(is_package package3)
		(is_package package4) 
		(is_package package5) 
		(is_package package6) 
		(is_package package7) 
		(is_package package8)
		(is_package package9)
		(is_package package10)
		(is_package package11)
		(is_package package12) 
		(is_package package13)
		(is_package package14) 
		(is_package package15) 
		(is_package package16) 
		(is_package package17) 
		(is_package package18)
		(is_package package19)
		(is_package package20)
		(in Athens Greece)
		(in Thessaloniki Greece)
		(in Larnaka Cyprus)
		(in Limassol Cyprus)
		(in Rome Italy)
		(in Bari Italy)
		(in Madrid Spain)
		(in warehouse_athens Athens)
		(in port_athens Athens)
		(in station_athens Athens)
		(in warehouse_thessaloniki Thessaloniki)
		(in port_thessaloniki Thessaloniki)
		(in station_thessaloniki Thessaloniki)
		(in port_larnaka Larnaka)
		(in port_limassol Limassol)
		(in warehouse_rome Rome)
		(in station_rome Rome)
		(in warehouse_bari Bari)
		(in port_bari Bari)
		(in station_bari Bari)
		(in warehouse_madrid Madrid)
		(in station_madrid Madrid)
		(at ship1 port_athens)
		(at ship2 port_larnaka)
		(at ship3 port_thessaloniki)
		(at ship4 port_limassol)
		(at ship5 port_bari)
		(unloaded ship1)
		(unloaded ship2)
		(unloaded ship3)
		(unloaded ship4)
		(unloaded ship5)
		(at truck1 warehouse_athens)
		(at truck2 station_athens)
		(at truck3 warehouse_thessaloniki)
		(at truck4 station_thessaloniki)
		(at truck5 port_athens)
		(at truck6 port_larnaka)
		(at truck7 port_thessaloniki)
		(at truck8 port_limassol)
		(at truck9 warehouse_rome)
		(at truck10 station_rome)
		(at truck11 port_bari)
		(at truck12 warehouse_bari)
		(at truck13 warehouse_madrid)
		(at truck14 station_madrid)
		(unloaded truck1)
		(unloaded truck2)
		(unloaded truck3)
		(unloaded truck4)
		(unloaded truck5)
		(unloaded truck6)
		(unloaded truck7)
		(unloaded truck8)
		(unloaded truck9)
		(unloaded truck10)
		(unloaded truck11)
		(unloaded truck12)
		(unloaded truck13)
		(unloaded truck14)
		(at locomotive1 station_athens)
		(at locomotive2 station_thessaloniki)
		(at locomotive3 station_rome)
		(at locomotive4 station_madrid)
		(at locomotive5 port_limassol)
		(at wagon1 station_athens)
		(at wagon2 station_athens)
		(at wagon3 station_athens)
		(at wagon4 station_thessaloniki)
		(at wagon5 station_thessaloniki)
		(at wagon6 station_thessaloniki)
		(at wagon7 station_rome)
		(at wagon8 station_rome)
		(at wagon9 station_rome)
		(at wagon10 station_madrid)
		(at wagon11 station_madrid)
		(at wagon12 station_madrid)
		(at wagon13 port_limassol)
		(at wagon14 port_limassol)
		(at wagon15 port_limassol)
		(unloaded wagon1)
		(unloaded wagon2)
		(unloaded wagon3)
		(unloaded wagon4)
		(unloaded wagon5)
		(unloaded wagon6)
		(unloaded wagon7)
		(unloaded wagon8)
		(unloaded wagon9)
		(unloaded wagon10)
		(unloaded wagon11)
		(unloaded wagon12)
		(unloaded wagon13)
		(unloaded wagon14)
		(unloaded wagon15)
		(free wagon1)
		(free wagon2)
		(free wagon3)
		(free wagon4)
		(free wagon5)
		(free wagon6)
		(free wagon7)
		(free wagon8)
		(free wagon9)
		(free wagon10)
		(free wagon11)
		(free wagon12)
		(free wagon13)
		(free wagon14)
		(free wagon15)
		(at package1 station_athens)
		(at package2 station_athens)
		(at package3 station_thessaloniki)
		(at package4 station_thessaloniki)
		(at package5 station_madrid)
		(at package6 station_madrid)
		(at package7 station_rome)
		(at package8 station_rome)
		(at package9 port_limassol)
		(at package10 port_limassol)
		(at package11 port_larnaka)
		(at package12 warehouse_rome)
		(at package13 warehouse_bari)
		(at package14 warehouse_madrid)
		(at package15 warehouse_athens)
		(at package16 warehouse_thessaloniki)
		(at package17 port_athens)
		(at package18 port_thessaloniki)
		(at package19 port_bari)
		(at package20 port_bari)
	)
	(:goal 	(and (at package1 station_madrid)
	            (at package2 station_rome)
	            (at package3 port_limassol)
	            (at package4 port_athens)
	            (at package5 port_limassol)
	            (at package6 station_rome)
	            (at package7 station_madrid)
	            (at package8 station_thessaloniki)
	            (at package9 station_thessaloniki)
	            (at package10 station_athens)
				(at package11 port_thessaloniki)
				(at package12 warehouse_athens)
	            (at package13 port_larnaka)
	            (at package14 station_athens)
	            (at package15 warehouse_madrid)
	            (at package16 port_bari)
	            (at package17 port_larnaka)
	            (at package18 port_bari)
	            (at package19 port_athens)
	            (at package20 port_thessaloniki))
	)
)
